# Generated by Django 3.1b1 on 2020-07-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('description', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('race', models.CharField(max_length=50, verbose_name='Raza')),
                ('age', models.CharField(choices=[('0', 'Cachoro'), ('1', 'Joven'), ('2', 'Adulto'), ('3', 'Anciano')], max_length=2, verbose_name='Edad')),
                ('state', models.CharField(choices=[('0', 'Disponible'), ('1', 'Adoptada')], max_length=2, verbose_name='Estado')),
                ('photo', models.ImageField(upload_to='', verbose_name='Fotografia')),
            ],
        ),
    ]
