# Generated by Django 3.1b1 on 2020-07-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_auto_20200725_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='age',
            field=models.CharField(choices=[('Cachorro', 'Cachoro'), ('Jpven', 'Joven'), ('Adulto', 'Adulto'), ('Anciano', 'Anciano')], max_length=8, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(upload_to='Dogs', verbose_name='Fotografia'),
        ),
    ]
