# Generated by Django 3.1b1 on 2020-07-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20200725_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
