# Generated by Django 3.1b1 on 2020-08-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_auto_20200726_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='description',
            field=models.TextField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
